
eureka:
  client:
    #To disable the Eureka Discovery Client, you can set eureka.client.enabled to false.
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    home-page-url-path: /
    status-page-url-path: /info
    health-check-url-path: /health
spring:
  application:
    name: luster-provider-client
server:
  port: 8080
